# Generated by Django 4.1.2 on 2022-11-12 08:56

from django.db import migrations, models
import shelf.models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='KotoPies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_mam_swira', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(validators=[shelf.models.validate_year]),
        ),
    ]
